services:
  - type: web
    name: between-us-server
    env: node
    plan: free
    buildCommand: npm install && npm run build --workspace=@between-us/shared && npm run build --workspace=@between-us/server
    startCommand: npm run start --workspace=@between-us/server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: between-us-client
    env: static
    buildCommand: npm install && npm run build --workspace=@between-us/shared && npm run build --workspace=@between-us/client
    staticPublishPath: packages/client/dist
    envVars:
      - key: VITE_SERVER_URL
        value: between-us-server-79k6.onrender.com
